### ISSUE TITLE
TypeError when using the special tag `!relative` to define `base_dir`

### ISSUE THREAD

**Issue by 9ao9ai9ar** [mikitex70/plantuml-markdown#103]
Since version 3.10.0, using the special tag [`!relative`](https://www.mkdocs.org/user-guide/configuration/#paths-relative-to-the-current-file-or-site) to define `base_dir`:

```yaml
# mkdocs.yml
docs_dir: docs
markdown_extensions:
  - plantuml_markdown:
      base_dir: !relative $docs_dir
```

will result in a TypeError during build:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\workspace\ssg\mkdocs\.venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\mkdocs\__main__.py", line 284, in build_command
    build.build(cfg, dirty=not clean)
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\mkdocs\commands\build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\mkdocs\commands\build.py", line 167, in _populate_page
    page.render(config, files)
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\mkdocs\structure\pages.py", line 285, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\markdown\core.py", line 354, in convert
    self.lines = prep.run(self.lines)
                 ^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\plantuml_markdown\plantuml_markdown.py", line 158, in run
    text1, idx1 = self._replace_block(text[idx:])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\ssg\mkdocs\.venv\Lib\site-packages\plantuml_markdown\plantuml_markdown.py", line 216, in _replace_block
    for base_dir in self._base_dir:
                    ^^^^^^^^^^^^^^
TypeError: 'DocsDirPlaceholder' object is not iterable
```

**Comment by mikitex70** [comment]
Hi @9ao9ai9ar, just released version `3.10.3` which fixes your issue.
Sorry for the inconvenience, I was not familiar with the `!relative` directive of MkDocs.
