### ISSUE TITLE
raising an error with mkdocs

### ISSUE THREAD

**Issue by ksimmi** [mikitex70/plantuml-markdown#29]
Hello,
I'm trying to use **plantuml-markdown** as mkdocs plugin but it raises an error: 

```
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/home/ksimmi/projects/tw/tengri_docs/venv/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 106, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 189, in _build_page
    site_navigation=site_navigation
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 59, in convert_markdown
    extension_configs=config['mdx_configs']
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 364, in convert_markdown
    extension_configs=extension_configs or {}
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
TypeError: extendMarkdown() takes exactly 2 arguments (3 given)
```

My **requirements.txt**:
```
appdirs==1.4.3
click==6.7
Jinja2==2.9.6
livereload==2.5.1
Markdown==2.6.8
MarkupSafe==1.0
mkdocs==0.16.3
mkdocs-bootswatch==0.4.0
plantuml-markdown==3.1.0
packaging==16.8
Pygments==2.2.0
pymdown-extensions==4.7
pyparsing==2.2.0
PyYAML==3.12
six==1.10.0
tornado==4.5.1
markdown-include==0.5.1
```

My **markdown_extensions** section from mkdocs.yml:
```
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - markdown_include.include:
  - plantuml_markdown:
      server: "http://www.plantuml.com/plantuml"
```

Could you help me please?
Thank you.

**Comment by mikitex70** [comment]
Fixed, try the plugin version `3.1.1`.
Thanks for reporting the issue.

**Comment by ksimmi** [comment]
Other error:
```
Traceback (most recent call last):
  File "/home/ksimmi/projects/tw/tengri_docs/venv/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 106, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 189, in _build_page
    site_navigation=site_navigation
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 59, in convert_markdown
    extension_configs=config['mdx_configs']
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 364, in convert_markdown
    extension_configs=extension_configs or {}
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/ksimmi/projects/tw/tengri_docs/venv/local/lib/python2.7/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'plantuml_markdown' from 'plantuml_markdown', 'markdown.extensions.plantuml_markdown' or 'mdx_plantuml_markdown'

```

**Comment by mikitex70** [comment]
Markdown 2.6 is a bit old... I need a bit more work to fix it.

**Comment by ksimmi** [comment]
Thank you!

**Comment by mikitex70** [comment]
There was an error in the package, an old file was added.
Try the new version 3.1.2.
