### ISSUE TITLE
exception if set kroki_server (version 3.7.0)

### ISSUE THREAD

**Issue by anb0s** [mikitex70/plantuml-markdown#78]
when set kroki_server i'm facing this exception in docs including plantuml disgrams:

```
- Platform/Services/Middleware/RUD_OAE_Middleware.md
ERROR    -  Error reading page 'Appendix/EditorialHints/Draft/Support/Layout/Layout.md': [Errno 2] No such file or directory: '/tmp/test/diag.puml'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line [140](https://code.siemens.com/oie-jupiter/documentation/arc-doc/-/jobs/91078215#L140)4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 131, in run
    text1, idx1 = self._replace_block(text[idx:])
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 189, in _replace_block
    diagram, err = self._render_diagram(code, requested_format, base_dir)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 287, in _render_diagram
    diagram, err = self._render_remote_uml_image(code, requested_format, base_dir)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 387, in _render_remote_uml_image
    with open('/tmp/test/diag.puml', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/test/diag.puml'
```

**Comment by nejch** [comment]
Fixed in 3.7.1 ;) https://github.com/mikitex70/plantuml-markdown/pull/77

**Comment by mikitex70** [comment]
Yes... I was interrupted during the release and I forgot about it, sorry.
Now is released on pypi.

**Comment by anb0s** [comment]
Thanks!
